"""create_slides_order_table

Revision ID: 60d1cb7c85d2
Revises: e758d23699f1
Create Date: 2023-11-25 01:12:54.255061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60d1cb7c85d2"
down_revision: Union[str, None] = "e758d23699f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slides_order",
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("slide_id", sa.Integer(), nullable=False),
        sa.Column("slide_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slide_id"], ["slides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id"),
        sa.UniqueConstraint("slide_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slides_order")
    # ### end Alembic commands ###
