"""create_users_progress_table

Revision ID: bb7e0fa3665e
Revises: 60d1cb7c85d2
Create Date: 2023-11-25 01:13:48.520468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb7e0fa3665e"
down_revision: Union[str, None] = "60d1cb7c85d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("current_lesson", sa.Integer(), nullable=False),
        sa.Column("current_slide", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["current_lesson"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["current_slide"], ["slides.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_progress")
    # ### end Alembic commands ###
