"""create_slides_table

Revision ID: e758d23699f1
Revises: a257707dd562
Create Date: 2023-11-25 01:12:01.240649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e758d23699f1"
down_revision: Union[str, None] = "a257707dd562"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slides",
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("keyboard", sa.String(), nullable=True),
        sa.Column(
            "slide_type",
            sa.Enum("INFO", "QUIZ_OPTIONS", "QUIZ_INPUT", name="slidetype"),
            nullable=False,
        ),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slides")
    # ### end Alembic commands ###
