"""create_lessons_table

Revision ID: a257707dd562
Revises: 1cfd2ea6c370
Create Date: 2023-11-25 01:10:23.947069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a257707dd562"
down_revision: Union[str, None] = "1cfd2ea6c370"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slide_amount", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="lessonlevel"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lessons")
    # ### end Alembic commands ###
